MsSQLAdmin/Controllers/DatabaseController.cs
using Microsoft.AspNetCore.Mvc;
using MsSQLAdmin.Services;
using MsSQLAdmin.Models;
using System.Threading.Tasks;
using System;

namespace MsSQLAdmin.Controllers {
    public class DatabaseController : Controller {
        private DatabaseService ServiceDatabase { get; set; }
        private ConnectionService ServiceConnection { get; set; }

        public DatabaseController(DatabaseService serviceDatabase, ConnectionService serviceConnection) {
            this.ServiceDatabase = serviceDatabase;
            this.ServiceConnection = serviceConnection;
        }

        [HttpGet("Server/{serveur}")]
        public async Task<IActionResult> Index([FromRoute]string serveur) {
            var model = this.ServiceConnection.GetDatabaseConnection();
            var models = await this.ServiceDatabase.GetDatabasesListAsync(model.ConnectionString);
            this.ServiceConnection.SetServeur(serveur);

            return View(models);
        }

        [HttpGet("Server/{serveur}/{database}")]
        public async Task<IActionResult> Tables([FromRoute]string serveur, [FromRoute]string database) {
            var model = this.ServiceConnection.GetDatabaseConnection();
            model.Database = database;

            this.ServiceConnection.SetDatabase(database);

            var models = await this.ServiceDatabase.GetDatabaseTablesListAsync(model.ConnectionString, database);
            return View(models);
        }

        [ResponseCache(Duration = 60)]//, VaryByQueryKeys = new string[] { "serveur", "database", "table" }
        [HttpGet("Server/{serveur}/{database}/{table}")]
        public async Task<IActionResult> Table([FromRoute]string serveur, [FromRoute] string database, [FromRoute]string table) {
            var connection = this.ServiceConnection.GetDatabaseConnection();
            connection.Database = database;

            this.ServiceConnection.SetDatabase(database);
            this.ServiceConnection.SetTable(table);

            TableViewModel model = new TableViewModel() {
                TableColumns = await this.ServiceDatabase.GetDatabaseTableDetailAsync(connection.ConnectionString, table)
            };

            return View(model);
        }

        [HttpPost("Server/{serveur}/Sql", Order = 1)]
        [HttpPost("Server/{serveur}/{database}/{table}", Order = 0)]
        public async Task<IActionResult> Data([FromRoute]string serveur, [FromRoute] string database, [FromRoute] string table, [FromForm] string sql) {
            var connection = this.ServiceConnection.GetDatabaseConnection();
            TableViewModel model = null;

            connection.Database = database;

            this.ServiceConnection.SetDatabase(database);
            this.ServiceConnection.SetTable(table);

            try {
                model = await this.ServiceDatabase.GetDataAsync(connection.ConnectionString, sql);
            } catch (Exception e) {
                model = new TableViewModel() { ErrorMessage = e.Message };
            }

            return PartialView("_Data", model);
        }

        [HttpGet("Server/{serveur}/Sql")]
        public IActionResult Sql([FromRoute]string serveur) {
            this.ServiceConnection.SetServeur(serveur);
            return View();
        }
    }
}

MsSQLAdmin/Controllers/SqlFormatController.cs
using Microsoft.AspNetCore.Mvc;
using MsSQLAdmin.Infrastructure;
using MsSQLAdmin.Models;

namespace MsSQLAdmin.Controllers {
    [Produces("application/json")]
    [Route("api/[controller]")]
    public class SqlFormatController : Controller {
        [HttpPost]
        [Route("FormatTSql")]
        public string FormatTSql([FromBody] FormatTSqlModel model) {
            return FormatTSqlWithOptions(new FormatTSqlModel() { InputString = model.InputString });
        }

        [HttpPost]
        [Route("FormatTSqlWithOptions")]
        public string FormatTSqlWithOptions([FromBody] FormatTSqlModel model) {
            PoorMansTSqlFormatterRedux.Interfaces.ISqlTreeFormatter formatter = null;
            if (model.ReFormat) {
                formatter = new PoorMansTSqlFormatterRedux.Formatters.TSqlStandardFormatter(new PoorMansTSqlFormatterRedux.Formatters.TSqlStandardFormatterOptions {
                    IndentString = model.Indent,
                    SpacesPerTab = model.SpacesPerTab,
                    MaxLineWidth = model.MaxLineWidth,
                    NewStatementLineBreaks = model.StatementBreaks,
                    NewClauseLineBreaks = model.ClauseBreaks,
                    ExpandCommaLists = model.ExpandCommaLists,
                    TrailingCommas = model.TrailingCommas,
                    SpaceAfterExpandedComma = model.SpaceAfterExpandedComma,
                    ExpandBooleanExpressions = model.ExpandBooleanExpressions,
                    ExpandCaseStatements = model.ExpandCaseStatements,
                    ExpandBetweenConditions = model.ExpandBetweenConditions,
                    BreakJoinOnSections = model.BreakJoinOnSections,
                    UppercaseKeywords = model.UppercaseKeywords,
                    HTMLColoring = model.Coloring,
                    KeywordStandardization = model.KeywordStandardization,
                    ExpandInLists = model.ExpandInLists
                });

            } else if (model.Obfuscate)
                formatter = new PoorMansTSqlFormatterRedux.Formatters.TSqlObfuscatingFormatter(
                  model.RandomizeKeywordCase,
                  model.RandomizeColor,
                  model.RandomizeLineLengths,
                  model.PreserveComments,
                  model.EnableKeywordSubstitution
                    );
            else
                formatter = new PoorMansTSqlFormatterRedux.Formatters.TSqlIdentityFormatter(model.Coloring);

            if (model.UseParseErrorPlaceholder)
                formatter.ErrorOutputPrefix = "{PARSEERRORPLACEHOLDER}";

            return FormatTSqlWithFormatter(model.InputString, formatter);
        }

        private string FormatTSqlWithFormatter(string inputString, PoorMansTSqlFormatterRedux.Interfaces.ISqlTreeFormatter formatter) {
            if (this.HttpContext.IsLocalRequest()) {
                PoorMansTSqlFormatterRedux.SqlFormattingManager fullFormatter = new PoorMansTSqlFormatterRedux.SqlFormattingManager(new PoorMansTSqlFormatterRedux.Formatters.HtmlPageWrapper(formatter));
                return fullFormatter.Format(inputString);
            } else {
                return "Sorry, this web service can only be called from code hosted at localhost.";
            }
        }
    }
}

MsSQLAdmin/Views/Database/Index.cshtml
@inject MsSQLAdmin.Services.ConnectionService ConnectionService
@model IEnumerable<MsSQLAdmin.Models.DatabaseModel>
@{
    ViewData["Title"] = "Index";
}

<h2>数据库</h2>

<p>

</p>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Size)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Tables", new { serveur = ConnectionService.Serveur, database = item.Name })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MsSQLAdmin/Views/Database/Sql.cshtml
@inject MsSQLAdmin.Services.ConnectionService ConnectionService
@model MsSQLAdmin.Models.TableViewModel
@{
    ViewData["Title"] = "Table";

    @if (string.IsNullOrWhiteSpace(ViewBag.SqlSelect)) {
        ViewBag.SqlSelect = $"SELECT TOP 1000 * FROM {ConnectionService.Table}";
    }
}
<h2>SQL</h2>
<div>
    <div class="panel panel-default">
        <div class="panel-body">
            <h2>SQL : </h2>
            <div class="row form-group">
                <div class="col-md-12">
                    <textarea id="sql" class="form-control">@Html.Raw(ViewBag.SqlSelect)</textarea>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-12">
                    <input type="button" id="sql_execute" value="Execute" class="btn btn-primary" />
                    <input type="button" id="sql_format" value="Format" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>

    @await Html.PartialAsync("_Data", Model)
</div>

@section Scripts {<!-- Create a simple CodeMirror instance -->
    <script>
        (function ($) {
            var editor;

            $(document).ready(function () {
                $('#data table').DataTable();

                editor = CodeMirror.fromTextArea($('#sql')[0], {
                    lineNumbers: true,
                    mode: 'text/x-sql',
                    indentWithTabs: true,
                    smartIndent: true,
                    lineNumbers: true,
                    matchBrackets: true
                });

                $('#data-tabs > li > a[aria-controls="Data"]').on('shown.bs.tab', function (e) {
                    console.log("test");

                    if (editor && editor instanceof CodeMirror) {
                        editor.refresh();
                    }
                });

                $('#sql_execute').on('click', function (e) {
                    $.ajax({
                        url: '@Url.Action("Data", "Database", new { serveur = ConnectionService.Serveur })',
                        method: "POST",
                        data: { sql: editor.getValue() }
                    }).done(function (result) {
                        $('#data').html(result);
                        $('#data table').DataTable();
                    });
                });

                $('#sql_format').on('click', function (e) {
                    $.ajax({
                        url: '@Url.Action("FormatTSqlWithOptions", "SqlFormat")',
                        method: "POST",
                        contentType: 'application/json',
                        data: JSON.stringify({ "inputString": editor.getValue(), "coloring": false })
                    }).done(function (result) {
                        editor.setValue(result);
                    });
                });
            });
        })(jQuery);
    </script>
}

MsSQLAdmin/Views/Database/Table.cshtml
@inject MsSQLAdmin.Services.ConnectionService ConnectionService
@model MsSQLAdmin.Models.TableViewModel
@{
    ViewData["Title"] = "Table";

    @if (string.IsNullOrWhiteSpace(ViewBag.SqlSelect)) {
        ViewBag.SqlSelect = $"SELECT TOP 1000 * FROM {ConnectionService.Table}";
    }
}
<h2>Table</h2>
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" id="data-tabs">
        <li role="presentation" class="active"><a href="#Structure" aria-controls="Structure" role="tab" data-toggle="tab">Structure</a></li>
        <li role="presentation"><a href="#Data" aria-controls="Data" role="tab" data-toggle="tab">Data</a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="Structure">
            @await Html.PartialAsync("_Structure", Model.TableColumns)
        </div>
        <div role="tabpanel" class="tab-pane" id="Data">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>SQL : </h2>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <textarea id="sql" class="form-control">@Html.Raw(ViewBag.SqlSelect)</textarea>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <input type="button" id="sql_execute" value="Execute" class="btn btn-primary" />
                            <input type="button" id="sql_format" value="Format" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
                    </div>

                    @await Html.PartialAsync("_Data", Model)
                </div>
    </div>
</div>

@section Scripts {<!-- Create a simple CodeMirror instance -->
    <script>
        (function ($) {
            var editor;

            $(document).ready(function () {
                $('#data table').DataTable();

                editor = CodeMirror.fromTextArea($('#sql')[0], {
                    lineNumbers: true,
                    mode: 'text/x-sql',
                    indentWithTabs: true,
                    smartIndent: true,
                    lineNumbers: true,
                    matchBrackets: true
                });

                $('#data-tabs > li > a[aria-controls="Data"]').on('shown.bs.tab', function (e) {
                    console.log("test");

                    if (editor && editor instanceof CodeMirror) {
                        editor.refresh();
                    }
                });

                $('#sql_execute').on('click', function (e) {
                    $.ajax({
                        url: '@Url.Action("Data", "Database", new { serveur = ConnectionService.Serveur, database = ConnectionService.Database, table = ConnectionService.Table })',
                        method: "POST",
                        data: { sql: editor.getValue() }
                    }).done(function (result) {
                        $('#data').html(result);
                        $('#data table').DataTable();
                    });
                });

                $('#sql_format').on('click', function (e) {
                    $.ajax({
                        url: '@Url.Action("FormatTSqlWithOptions", "SqlFormat")',
                        method: "POST",
                        contentType: 'application/json',
                        data: JSON.stringify({ "inputString": editor.getValue(), "coloring": false })
                    }).done(function (result) {
                        editor.setValue(result);
                    });
                });
            });
        })(jQuery);
    </script>
}

MsSQLAdmin/Views/Database/Tables.cshtml
@inject MsSQLAdmin.Services.ConnectionService ConnectionService
@model IEnumerable<MsSQLAdmin.Models.TableListModel>
@{
    ViewData["Title"] = "Tables";
}
<h2>Tables</h2>
<p>
   
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Schema)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Schema)
                </td>
                <td>
                    @Html.ActionLink(item.Name, "Table", new { serveur = ConnectionService.Serveur, database = ConnectionService.Database, table = $"{item.Schema}.{item.Name}" })
                </td>
                <td>
                   
                </td>
            </tr>
        }
    </tbody>
</table>

MsSQLAdmin/Views/Database/_Data.cshtml
@model MsSQLAdmin.Models.TableViewModel
<div class="table-responsive" id="data">
    @if (Model != null) {
        @if (Model.TableData != null) {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Row</th>
                        @foreach (var column in Model.TableColumns) {
                            <th>
                                @Html.Raw(column.Name)
                            </th>
                        }
                    </tr>
                </thead>
                @if (Model.TableData != null && Model.TableData.Count() > 0) {
                    <tbody>
                        @for (int i = 0; i < Model.TableData.Count(); i++) {
                            var row = Model.TableData[i];
                            <tr>
                                <td>@i</td>
                                @foreach (var column in Model.TableColumns) {
                                    <td>
                                        @Html.Raw(row[column.Name])
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                }
            </table>
        } else if (!string.IsNullOrWhiteSpace(Model.ErrorMessage)) {
            <div class="alert alert-danger" role="alert">@Model.ErrorMessage</div>
        } else {
            <div class="alert alert-info" role="alert">
                <strong>@Model.DDLResult</strong>enregistrement(s) mis à jour
            </div>
        }
    }
</div>

MsSQLAdmin/Views/Database/_Structure.cshtml
@model IEnumerable<MsSQLAdmin.Models.TableColumnModel>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaxLength)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precision)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Scale)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsNullable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsPrimaryKey)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxLength)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precision)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Scale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsNullable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsPrimaryKey)
                    </td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
</div>